### ISSUE TITLE
Running exec.Command in OnPanic handler causes wait: no child processes error

### ISSUE THREAD

**Issue by APshenkin** [grongor/panicwatch#24]
Running `exec.Command` in `OnPanic` causes `wait: no child processes` in err. However it seems command is actually executed as stdout contains command result output.

Check out repo for example https://github.com/APshenkin/panicwatch-cmd-run

Is there any way to prevent err to appear?

**Comment by grongor** [comment]
Hi! Sorry for the delay; I just noticed your issue when doing some other things around here :) Great catch! Thanks for nicely isolated example. I think I've found a fix (see the linked PR)...I'll merge and tag it in a few minutes ;)
